version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: AsesorIA
    restart: unless-stopped
    environment:
      - N8N_HOST=n8n-tunnel.tfm4ucm.org
      - N8N_PROTOCOL=https                # <-- IMPORTANTE
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8n-tunnel.tfm4ucm.org   # <-- sin barra final
      - N8N_EDITOR_BASE_URL=https://n8n-tunnel.tfm4ucm.org
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - n8n-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - n8n-net

networks:
  n8n-net:
    driver: bridge
