name: Ejecutar Scraper Diario

on:
  schedule:
    - cron: '0 6 * * *'  # Ejecuta todos los días a las 6:00 UTC (~1 AM Lima/Madrid)
  workflow_dispatch:      # Permite ejecutar manualmente desde GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script principal
        run: |
          python main.py

      # Opcional: enviar notificación a n8n
      - name: Notificar a n8n
        if: success()  # Solo si todo fue bien
        run: |
          curl -X POST https://TU_WEBHOOK_DE_N8N.com/webhook/ejecutado \
            -H "Content-Type: application/json" \
            -d '{"estado": "ok", "origen": "GitHub Actions", "timestamp": "'$(date -u)'"}'
