name: Update index constituents (Snowflake)

on:
  schedule:
    # Corre todos los días a las 05:15 UTC  (07:15 en Madrid durante CEST)
    - cron: '15 5 * * *'
  workflow_dispatch: {}   # permite lanzarlo a mano

permissions:
  contents: read

concurrency:
  group: update-index-constituents
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      TZ: Europe/Madrid
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_TABLE: ${{ secrets.SNOWFLAKE_TABLE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas snowflake-connector-python beautifulsoup4 lxml

      - name: Run scraper & load to Snowflake
        working-directory: Yahoo_prueba   # <--- tu carpeta
        run: python tickers_global.py

      # (Opcional) Notificación a n8n/Discord/Slack si todo OK
      # - name: Notify webhook
      #   if: success()
      #   run: |
      #     curl -sS -X POST "$N8N_URL/webhook/scraping-finalizado" \
      #       -H "Content-Type: application/json" \
      #       -H "x-n8n-secret: $N8N_WEBHOOK_SECRET" \
      #       --data "$(jq -n --arg status ok --arg msg 'Constiuents updated' \
      #                         '{status:$status, mensaje:$msg}')"
